version: 0.0

os: linux

files:
    - souce: /aws-codedeploy
      destination: /app/
    - source: /index.html
      destination: /index.html
    - source: /config.json
      destination: /app/

hooks:
    ApplicationStop:
        - location: scripts/stop.sh
          timeout: 180
          runas: ubuntu
    BeforeInstall:
        - location: scripts/cleanup.sh
          timeout: 180
          runas: ubuntu
    ApplicationStart:
        - location: scripts/start.sh
          timeout: 180
          runas: ubuntu
